
config:
  # Overriden in helmfile
  # ipfs: https://ipfs.network.thegraph.com

  # Configuration of connected blockchain metrics and their providers
  chains:
    mainnet:
      providers:
      - label: mainnet
        url: "https://magical-still-grass.quiknode.pro/653d5fa3dd62f717496030b69e5c2b70aa16dfd1/"
        features: [ archive, traces ]
    # rinkeby:
    #   providers:
    #   - label: rinkeby
    #     url:
    #     features: [ archive ]

postgres:
  db: graph
  host: 10.32.66.2
  # replicaHost: postgres-postgres-repl
  user: graphnode
  password:
    fromSecret:
      # Create graph-pg password:
      # 
      name: graph-pg
      key: password

resources:
  requests:
    cpu: 4
    memory: 6Gi
  limits:
    cpu: 6
    memory: 7.5Gi
    # ephemeral-storage: 10Gi
  

role: "index-node"

monitoring:
  enabled: false
