apiVersion: v1
kind: Service
metadata:
  name: graph-node-internal-lb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/instance: graphprotocol-node-index
  ports:
  - name: graph-indexer-8020
    protocol: TCP
    port: 8020
    targetPort: 8020
  - name: graph-indexer-8030
    protocol: TCP
    port: 8030
    targetPort: 8030
  - name: graph-indexer-8040
    protocol: TCP
    port: 8040
    targetPort: 8040    
  - name: graph-indexer-8001
    protocol: TCP
    port: 8001
    targetPort: 8001    
  - name: graph-indexer-8000
    protocol: TCP
    port: 8000
    targetPort: 8000  